sonar.java.binaries=srv/target/classes 
sonar.java.test.binaries=srv/target/test-classes 
sonar.junit.reportPaths=srv/target/surefire-reports 
sonar.sources=srv/src/main/java 
sonar.tests=srv/src/test/java 
sonar.coverage.jacoco.xmlReportPaths=srv/target/site/jacoco/jacoco.xml